### ISSUE TITLE
Unable to download files from Downloads.md

### ISSUE THREAD

**Issue by MaxTeselkin** [mlzxy/devit#7]
Hi! I tried downloading files from your google drive as proposed in Downloads.md:

`gdown 1b3anUR2Gloh7XpvevPCuxWeYCvQJ7Pfz --folder`

 but got the following error:

<img width="561" alt="image" src="https://github.com/mlzxy/devit/assets/91027877/ad435959-ae12-47c8-993c-22519ecc924d">

I also had problems with downloading files because of google drive limitations (if too many people download specific file in a short period of time, google drive will temporary disable access to it).

I understand that I still can download these files from browser, but it is not convenient way since I am working via remote ssh, not from my local machine.

**Comment by mlzxy** [comment]
This indeed happens sometimes. My suggestion is to try rclone https://rclone.org/drive/ .  The below procedure definitely works because I also use it a lot.

Procedure:

1. Copy the share folder to your google drive (Add shortcut to Drive)
2. Configure rclone with google drive
3. download the folder by `rclone copy` from your google drive

**Comment by mlzxy** [comment]
Also use `rclone ls` before `copy` to make sure you are downloading the right folder. This is the guaranteed way to download from google drive.

**Comment by MaxTeselkin** [comment]
Thanks for advice

**Comment by Djanghao** [comment]
the problem is gone:

![Image](https://github.com/user-attachments/assets/43e950ae-5d1a-4345-958b-8dda7e4894e6)
