### ISSUE TITLE
OSOD task on COCO2017 error "ValueError: 'person' is not in list"

### ISSUE THREAD

**Issue by Seaz9** [mlzxy/devit#74]
Hi @mlzxy ,
When performing the OSOD task on COCO2017, I encountered an issue with using `devit_update.py`, which throws the error "ValueError: 'person' is not in list". However, when using `devit.py`, the model can train and validate normally. I would like to ask which part of `devit_update.py` I should modify to enable the model to train and validate correctly?
best，
hongliang

the error
“
MODEL:
  META_ARCHITECTURE: "OpenSetDetectorWithExamples_refactored"
  BACKBONE:
    NAME: "build_dino_v2_vit"
    TYPE: "large"
  WEIGHTS: "" 
  MASK_ON: False
  RPN:
    HEAD_NAME: StandardRPNHead
    IN_FEATURES: ["res4"]
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.001
  ROI_BOX_HEAD:
    NAME: ""
    NUM_FC: 0
    POOLER_RESOLUTION: 7
    CLS_AGNOSTIC_BBOX_REG: True
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("coco_2017_train_oneshot_s1",)
  TEST: ("coco_2017_val",)
TEST:
  EVAL_PERIOD: 100
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.002
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 5000
  CHECKPOINT_PERIOD: 100

INPUT:
  MIN_SIZE_TRAIN_SAMPLING: choice
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  FORMAT: "RGB"

# OUTPUT_DIR: output

[11/15 17:04:26 detectron2]: Full config saved to /root/autodl-tmp/devit-main/output/train/one-shot/split1/vitl/config.yaml
[11/15 17:04:26 d2.utils.env]: Using a generated random seed 26600174
('coco_2017_val',)
Traceback (most recent call last):
  File "/root/autodl-tmp/devit-main/tools/train_net.py", line 208, in <module>
    launch(
  File "/root/autodl-tmp/devit-main/tools/../detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/root/autodl-tmp/devit-main/tools/train_net.py", line 195, in main
    trainer = Trainer(cfg)
  File "/root/autodl-tmp/devit-main/tools/../detectron2/engine/defaults.py", line 377, in __init__
    model = self.build_model(cfg)
  File "/root/autodl-tmp/devit-main/tools/../detectron2/engine/defaults.py", line 517, in build_model
    model = build_model(cfg)
  File "/root/autodl-tmp/devit-main/tools/../detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/root/autodl-tmp/devit-main/tools/../detectron2/config/config.py", line 176, in wrapped
    init_func(self, **explicit_args)
  File "/root/autodl-tmp/devit-main/tools/../detectron2/modeling/meta_arch/devit_update.py", line 466, in __init__
    test_class_order = [prototype_label_names.index(c) for c in all_cids]
  File "/root/autodl-tmp/devit-main/tools/../detectron2/modeling/meta_arch/devit_update.py", line 466, in <listcomp>
    test_class_order = [prototype_label_names.index(c) for c in all_cids]
ValueError: 'person' is not in list
Traceback (most recent call last):
  File "/root/autodl-tmp/devit-main/train.py", line 73, in <module>
    run_command(command)
  File "/root/autodl-tmp/devit-main/train.py", line 30, in run_command
    subprocess.run(command, shell=True, check=True)
  File "/root/miniconda3/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python /root/autodl-tmp/devit-main/tools/train_net.py --num-gpus 1 --config-file /root/autodl-tmp/devit-main/configs/one-shot/split1_vitl.yaml MODEL.WEIGHTS /root/autodl-tmp/devit-main/weights/initial/oneshot/vitl+rpn.split1.pth DE.OFFLINE_RPN_CONFIG /root/autodl-tmp/devit-main/configs/RPN/mask_rcnn_R_50_C4_1x_ovd_FSD.yaml OUTPUT_DIR /root/autodl-tmp/devit-main/output/train/one-shot/split1/vitl/ DE.ONE_SHOT_MODE True' returned non-zero exit status 1.
”

**Comment by mlzxy** [comment]
There are mainly two differences between normal evaluation and one-shot
evaluation.

   1. One-shot evaluation is a single class detection
   2. During one-shot evaluation, the model randomly sample from a large
   pool of images to use as prototype, instead of using the same 10/30 images
   as few-shot evaluation.


You can search for use_one_shot to find all one-shot evaluation branches in
devit.py
<https://github.com/mlzxy/devit/blob/main/detectron2/modeling/meta_arch/devit.py>
.


   1. Loading the one-shot reference image features, these features are
   created from COCO validation set (L633
   <https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/detectron2/modeling/meta_arch/devit.py#L633>
   )
   2. Randomly swap prototype features with reference image during testing (
   L989
   <https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/detectron2/modeling/meta_arch/devit.py#L989>
   )
   3. Record target class id from ground truth (knowing what
   classes actually  appear in the image (L1024
   <https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/detectron2/modeling/meta_arch/devit.py#L1024>
   )
      1. And use them in step4
      2. Note the self.training is still False, so we won’t filter the
      proposals with ground truth information.
   4. Go through all target class id (the classes that actually appear in
   the image, based on groundtruth), and only keep the score of these objects
   by creating a copy of all boxes, and only set the scores of this object
   class (L1412
   <https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/detectron2/modeling/meta_arch/devit.py#L1412>
   )
      1. Does it mean we assume the knowledge that what type of objects
      will appear in the image? Yes.
      2. This essentially simulate the process of only detect certain
      class.
      3. Based on my experiments, selecting certain class from output
      yields very similar results to having only a single class in the
      prototypes, but runs much faster.


I basically borrow the setting from this codebase
https://github.com/hero-y/BHRL.  You basically need to copy paste these
sections of code and make some small adjustments I guess.

Good luck and let me know if you have more questions.

**Comment by mlzxy** [comment]
There are mainly two differences between normal evaluation and one-shot
evaluation.

   1. One-shot evaluation is a single class detection
   2. During one-shot evaluation, the model randomly sample from a large pool of images to use as prototype, instead of using the same 10/30 images as few-shot evaluation.


You can search for use_one_shot to find all one-shot evaluation branches in
[devit.py](https://github.com/mlzxy/devit/blob/main/detectron2/modeling/meta_arch/devit.py).


   1. Loading the one-shot reference image features, these features are  created from COCO validation set ([L633](https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/detectron2/modeling/meta_arch/devit.py#L633))
   2. Randomly swap prototype features with reference image during testing ([L989](https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/detectron2/modeling/meta_arch/devit.py#L989))
   3. Record target class id from ground truth (knowing what classes actually  appear in the image ([L1024](https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/detectron2/modeling/meta_arch/devit.py#L1024))
      1. And use them in step4
      2. Note the self.training is still False, so we won’t filter the proposals with ground truth information.
   4. Go through all target class id (the classes that actually appear in the image, based on groundtruth), and only keep the score of these objects by creating a copy of all boxes, and only set the scores of this object class ([L1412](https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/detectron2/modeling/meta_arch/devit.py#L1412))
      1. Does it mean we assume the knowledge that what type of objects will appear in the image? Yes.
      2. This essentially simulate the process of only detect certain class.
      3. Based on my experiments, selecting certain class from output yields very similar results to having only a single class in the prototypes, but runs much faster.


I basically borrow the setting from this codebase https://github.com/hero-y/BHRL.  You basically need to copy paste these sections of code and make some small adjustments I guess.

Good luck and let me know if you have more questions.

**Comment by Seaz9** [comment]
> There are mainly two differences between normal evaluation and one-shot evaluation.
> 
> 1. One-shot evaluation is a single class detection
> 2. During one-shot evaluation, the model randomly sample from a large pool of images to use as prototype, instead of using the same 10/30 images as few-shot evaluation.
> 
> You can search for use_one_shot to find all one-shot evaluation branches in [devit.py](https://github.com/mlzxy/devit/blob/main/detectron2/modeling/meta_arch/devit.py).
> 
> 1. Loading the one-shot reference image features, these features are  created from COCO validation set ([L633](https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/detectron2/modeling/meta_arch/devit.py#L633))
> 2. Randomly swap prototype features with reference image during testing ([L989](https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/detectron2/modeling/meta_arch/devit.py#L989))
> 3. Record target class id from ground truth (knowing what classes actually  appear in the image ([L1024](https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/detectron2/modeling/meta_arch/devit.py#L1024))
>    
>    1. And use them in step4
>    2. Note the self.training is still False, so we won’t filter the proposals with ground truth information.
> 4. Go through all target class id (the classes that actually appear in the image, based on groundtruth), and only keep the score of these objects by creating a copy of all boxes, and only set the scores of this object class ([L1412](https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/detectron2/modeling/meta_arch/devit.py#L1412))
>    
>    1. Does it mean we assume the knowledge that what type of objects will appear in the image? Yes.
>    2. This essentially simulate the process of only detect certain class.
>    3. Based on my experiments, selecting certain class from output yields very similar results to having only a single class in the prototypes, but runs much faster.
> 
> I basically borrow the setting from this codebase https://github.com/hero-y/BHRL. You basically need to copy paste these sections of code and make some small adjustments I guess.
> 
> Good luck and let me know if you have more questions.

Thank you, I will try modifying the code and add the parts you mentioned.
